sudo: required
services:
  - docker

before_install:
  - docker build -t liu-lian/react-test -f ./client/Dockerfile.dev ./client
  # - docker build -t liu-lian/anotherApp ....

script:
  - docker run -e CI=true liu-lian/react-test npm test
  # - docker run liu-lian/anotherApp npm test 

after_success:
  - docker build -t liu-lian/multi-client ./client
  - docker build -t liu-lian/multi-nginx ./nginx
  - docker build -t liu-lian/multi-server ./server
  - docker build -t liu-lian/multi-worker ./worker
  # Log in to the docker CLI
  # at CLI: docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push liu-lian/multi-client
  - docker push liu-lian/multi-nginx
  - docker push liu-lian/multi-server
  - docker push liu-lian/multi-worker
   
   
   
   
